/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zyl_ndkdemo001_cpp_HelloNDK */

#ifndef _Included_com_zyl_ndkdemo001_cpp_HelloNDK
#define _Included_com_zyl_ndkdemo001_cpp_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zyl_ndkdemo001_cpp_HelloNDK
 * Method:    stringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zyl_ndkdemo001_cpp_HelloNDK_stringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
